Attempt to handle backends that do not have a renderer method
Sme backends cause:

> AttributeError: 'FigureCanvasMac' object has no attribute 'get_renderer'

So I've modifed Grf to use the trick described at:
http://stackoverflow.com/questions/22667224/matplotlib-get-text-bounding-box-independent-of-backend